networks:
  notify:

services:

  nginx-service:
    container_name: nginx-container
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-service
      - db-service
    networks:
      - notify

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - notify

  php-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      XDEBUG_CONFIG: remote_enable=1 remote_host=host.docker.internal remote_port=9000 remote_autostart=1 remote_connect_back=0
      PHO_IDE_CONFIG: "serviceName=Docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - notify

  db-service:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notify

volumes:
  db_data:
