networks:
  notify:

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/conf.d/custom.ini:/etc/php/conf.d/php.ini
    container_name: php8
    networks:
      - notify

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - notify

  db-service:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notify

volumes:
    db_data:



